name: check-latest-envoy-version
on:
  push:
    branches:
      - rulex123:scheduled-workflow
      - scheduled-workflow
    outputs:
      result:
        description: "Do we need to update the Envoy API or not?"
        value: ${{ jobs.latest.outputs.output1 }}

#  schedule:
#    # every Monday at 10
#    - cron:  '0 10 * * 1'

jobs:
  check-latest-envoy-version:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.action }}
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest Envoy version
        run: |
          echo 'ENVOY_LATEST<<EOF' >> $GITHUB_ENV
          curl -s https://api.github.com/repos/envoyproxy/envoy/releases/latest | jq -r '.tag_name' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Read current Envoy version
        run: |
          echo 'ENVOY_CURRENT<<EOF' >> $GITHUB_ENV
          cat current_version >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Compare current to latest
        id: step1
        run: |
          if [[ "${{ env.ENVOY_LATEST}}" == "${{ env.ENVOY_CURRENT}}" ]]
          then
            echo We are already on the latest Envoy version!"
            echo {ACTION}={none} >> $GITHUB_ENV
            echo "::set-output name=action::none"
          else
            echo "We are behind, I will trigger the workflow that updates the Envoy API!"
            echo {ACTION}={trigger} >> $GITHUB_ENV
            echo "::set-output name=action::trigger"
            echo "::set-output name=version::${{ env.ENVOY_LATEST}}"
          fi

  call-update-protobuf-workflow:
    needs: check-latest-envoy-version
    if: ${{ needs.check-latest-envoy-version.outputs.result == 'trigger' }}
    uses: ./.github/workflows/update-protobuf.yml
    with:
      envoy_version: ${{ env.ENVOY_LATEST }}
