name: check-latest-envoy-version
on:
  push:
    branches:
      - rulex123:scheduled-workflow
      - scheduled-workflow
#  schedule:
#    # every Monday at 10
#    - cron:  '0 10 * * 1'

jobs:
  check-latest-envoy-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest Envoy version
        run: |
          echo 'ENVOY_LATEST<<EOF' >> $GITHUB_ENV
          curl -s https://api.github.com/repos/envoyproxy/envoy/releases/latest | jq -r '.tag_name' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Read current Envoy version
        run: |
          echo 'ENVOY_CURRENT<<EOF' >> $GITHUB_ENV
          cat current_version >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Compare current to latest
        run: |
          if [[ "${{ env.ENVOY_LATEST}}" == "${{ env.ENVOY_CURRENT}}" ]]
          then
            echo "we are already on latest version!"
          else
            echo "we are behind!"
          fi
